// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqZaSVdqLrrn0Hkeo-gKsh5vLB-6KEV4',
    appId: '1:79590235864:web:69e3f6591a79d8eff901ad',
    messagingSenderId: '79590235864',
    projectId: 'covid19-tracker-9eca1',
    authDomain: 'covid19-tracker-9eca1.firebaseapp.com',
    storageBucket: 'covid19-tracker-9eca1.appspot.com',
    measurementId: 'G-NZYWRSRE8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxd92AVX7JoU_N22KPY5ZfhuCwjHV3UQ',
    appId: '1:79590235864:android:14c8745cd04458f1f901ad',
    messagingSenderId: '79590235864',
    projectId: 'covid19-tracker-9eca1',
    storageBucket: 'covid19-tracker-9eca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1KtqApZyPeibTZMkWJQ1EVPsRv86nM0Y',
    appId: '1:79590235864:ios:c08369ea74a577c1f901ad',
    messagingSenderId: '79590235864',
    projectId: 'covid19-tracker-9eca1',
    storageBucket: 'covid19-tracker-9eca1.appspot.com',
    iosClientId: '79590235864-5ua0qer3975qgf738smaj5s67brguq7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.covid19Tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1KtqApZyPeibTZMkWJQ1EVPsRv86nM0Y',
    appId: '1:79590235864:ios:d9b460e294770d46f901ad',
    messagingSenderId: '79590235864',
    projectId: 'covid19-tracker-9eca1',
    storageBucket: 'covid19-tracker-9eca1.appspot.com',
    iosClientId: '79590235864-jvpsecp2qs6bqr53b0c9ic8g2t5ppqsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.covid19Tracker.RunnerTests',
  );
}
